-- RapidTrader Complete Database Schema for Supabase

-- CORE TABLES

-- Symbol universe with sector classification
CREATE TABLE IF NOT EXISTS symbols (
    symbol TEXT PRIMARY KEY,
    name TEXT,
    sector TEXT,
    sub_sector TEXT,
    is_active BOOLEAN DEFAULT true,
    date_added DATE DEFAULT CURRENT_DATE
);

-- Daily OHLCV bars
CREATE TABLE IF NOT EXISTS bars_daily (
    symbol TEXT,
    d DATE,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume INTEGER NOT NULL,
    PRIMARY KEY (symbol, d),
    FOREIGN KEY (symbol) REFERENCES symbols(symbol)
);

-- Trading signals with strength
CREATE TABLE IF NOT EXISTS signals_daily (
    d DATE NOT NULL,
    symbol TEXT NOT NULL,
    strategy TEXT NOT NULL,
    direction TEXT NOT NULL,
    strength REAL,
    metadata JSONB,
    PRIMARY KEY (d, symbol, strategy),
    FOREIGN KEY (symbol) REFERENCES symbols(symbol)
);

-- Generated orders (dry-run)
CREATE TABLE IF NOT EXISTS orders_eod (
    id SERIAL PRIMARY KEY,
    d DATE NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    qty INTEGER NOT NULL,
    type TEXT NOT NULL,
    price REAL,
    reason TEXT,
    strategy TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol) REFERENCES symbols(symbol)
);

-- Position tracking
CREATE TABLE IF NOT EXISTS positions (
    symbol TEXT PRIMARY KEY,
    qty INTEGER NOT NULL,
    avg_px REAL NOT NULL,
    sector TEXT,
    entry_date DATE,
    stop_price REAL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol) REFERENCES symbols(symbol)
);

-- Market state cache (SPY data)
CREATE TABLE IF NOT EXISTS market_state (
    d DATE PRIMARY KEY,
    spy_close REAL NOT NULL,
    spy_sma200 REAL,
    bull_gate BOOLEAN,
    volume_avg_20d REAL,
    volatility_20d REAL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stop loss events and cooldown tracking
CREATE TABLE IF NOT EXISTS symbol_events (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    event TEXT NOT NULL,
    d DATE NOT NULL,
    price REAL,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol) REFERENCES symbols(symbol)
);

-- SUPPORTING TABLES

-- SIC codes for sector classification
CREATE TABLE IF NOT EXISTS sic_codes (
    sic_code INTEGER PRIMARY KEY,
    sec_office TEXT NOT NULL,
    sic_description TEXT NOT NULL,
    gics_sector TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sector cache for company data
CREATE TABLE IF NOT EXISTS sector_cache (
    symbol TEXT PRIMARY KEY,
    sector TEXT,
    sic_description TEXT,
    sic_code TEXT,
    last_updated DATE,
    FOREIGN KEY (symbol) REFERENCES symbols(symbol)
);

-- System kill state and trading permissions
CREATE TABLE IF NOT EXISTS system_state (
    d DATE PRIMARY KEY,
    kill_active BOOLEAN NOT NULL DEFAULT FALSE,
    reason TEXT,
    resume_eligible_d DATE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Execution fills for reconciliation
CREATE TABLE IF NOT EXISTS exec_fills (
    id BIGSERIAL PRIMARY KEY,
    d DATE NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    qty INTEGER NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL,
    venue TEXT,
    broker_order_id TEXT,
    strategy TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- TRIGGERS AND FUNCTIONS

-- Update trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to system_state
DROP TRIGGER IF EXISTS update_system_state_updated_at ON system_state;
CREATE TRIGGER update_system_state_updated_at
    BEFORE UPDATE ON system_state
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- INDEXES FOR PERFORMANCE

CREATE INDEX IF NOT EXISTS idx_bars_daily_symbol ON bars_daily(symbol);
CREATE INDEX IF NOT EXISTS idx_bars_daily_d ON bars_daily(d);
CREATE INDEX IF NOT EXISTS idx_signals_daily_d ON signals_daily(d);
CREATE INDEX IF NOT EXISTS idx_orders_eod_d ON orders_eod(d);
CREATE INDEX IF NOT EXISTS idx_symbol_events_symbol ON symbol_events(symbol);
CREATE INDEX IF NOT EXISTS idx_system_state_d ON system_state(d);
CREATE INDEX IF NOT EXISTS idx_exec_fills_d_symbol ON exec_fills(d, symbol);
CREATE INDEX IF NOT EXISTS idx_exec_fills_broker_order_id ON exec_fills(broker_order_id);

-- TABLE COMMENTS (Documentation)

COMMENT ON TABLE symbols IS 'S&P 500 symbols with sector classification';
COMMENT ON TABLE bars_daily IS 'Daily OHLCV market data';
COMMENT ON TABLE signals_daily IS 'Trading signals generated by strategies';
COMMENT ON TABLE orders_eod IS 'Generated orders for paper/live trading';
COMMENT ON TABLE positions IS 'Current portfolio positions';
COMMENT ON TABLE market_state IS 'SPY market filter cache';
COMMENT ON TABLE symbol_events IS 'Stop loss and other trading events';
COMMENT ON TABLE sic_codes IS 'SEC Standard Industrial Classification codes';
COMMENT ON TABLE sector_cache IS 'Cached sector and industry data for symbols';
COMMENT ON TABLE system_state IS 'Tracks kill switch state and trading permissions by date';
COMMENT ON TABLE exec_fills IS 'Records actual broker executions for reconciliation';
